### ISSUE TITLE
Incluir campo Meta para Nota Final e Alterar Escala de Cores

### ISSUE THREAD

**Issue by alex-sousa** [llms/sialg#14]
Leo, 

- Incluir campo que permita alterar a meta para a Nota Final (sendo o valor padrão10, numérico). O campo deve atualizar a consulta, como os demais.

- Somente quem tiver Nota Final >= 7 deverá ter a imagem de medalha na coluna "Medalha". No caso aquele icone de medalha apareceriam com cores diferentes de acordo

Critérios para as Medalhas
Nota Final >= 120% da Meta - Diamante
Nota Final >= 100% e < 120% da Meta - Ouro
Nota Final >= 85% e < 100% da Meta - Prata
Nota Final >= 70% e < 85% da Meta - Bronze

O percentual é com relação a Meta da Nota Final, que é 10.

- Os 10 primeiros, ordenados pela Nota Final, deverão ter uma cor de fundo diferente nas células "Medalhas", "Rank" e "GEA" (ou CEDES). 

- Todas as demais colunas das tabelas, inclusive Nota Final (e cores dos dials) devem seguir a mesma escala de cores abaixo:

**Critérios desempenho cada indicador (cores)**	
% Resultado >= 120%	COR AZUL	MUITO SATISFATÓRIO	
% Resultado >= 100% e < 120% 	COR VERDE	SATISFATÓRIO	
% Resultado >= 70% e < 100% 	COR AMARELA	NECESSITA DE MELHORIAS	
% Resultado < 70%	COR VERMELHA	NECESSITA DE MELHORIAS IMPORTANTES	
Os percentuais são sempre com relação aos valores das Metas de cada Visão.	

![image](https://cloud.githubusercontent.com/assets/22936150/21849112/44111b02-d7eb-11e6-898f-88ae52e7dec0.png)

**Comment by alex-sousa** [comment]
Leo, segue a escala de cores pra tabela, incluindo o cabeçalho.
O que estiver fora dessa escala (<70) fica em fundo branco mesmo.
No final a Fernanda pediu para incluir uma legenda de cores. Com a cor e esses "Muito Satisfatório", "Satisfatório", etc
![image](https://cloud.githubusercontent.com/assets/22936150/21988469/7b242966-dbee-11e6-8a94-9cd0f5432944.png)




![image](https://cloud.githubusercontent.com/assets/22936150/21988181/83129fdc-dbed-11e6-86fa-04611b71c20a.png)

**Comment by JulianaCarvalho** [comment]
closes #14
