### ISSUE TITLE
Alteração na Disposição dos Gráficos

### ISSUE THREAD

**Issue by alex-sousa** [llms/sialg#15]
- Gráfico
            - retirar o gráfico da nota final;
            - Sugiro a seguinte disposição para que todos os gráficos tenham a mesma proporção. Dessa forma podemos aumentar mais um pouco a largura das barras.

![image](https://cloud.githubusercontent.com/assets/22936150/21988308/ed97e7e0-dbed-11e6-9384-5d0236b8276b.png)

**Comment by JulianaCarvalho** [comment]
closes #15
