### ISSUE TITLE
Detalhar demandas ao clicar Linha da Tabela

### ISSUE THREAD

**Issue by alex-sousa** [llms/sialg#19]
Acima da tabela Título trará Sigla GEC/Sigla Coord TI selecionada
Abaixo do título em menor destaque: Qt Pontos de Função SUCTI 0,00 / PF por Empregado: 0,00
Os campos listados em itálico deverão ser mesclados na tabela, se trouxerem os mesmos valores.

**Campos da Tabela**
_ID RTC Pai
Status Demanda Pai
Sigla Sistema	
Tipo de Demanda Pai	
Planejado Para
Prioridade
Data de Resolução (Pai)	
Qt Replanejamento_	
ID RTC Filha	
Tipo de Demanda Filha	
Status Demanda Filha	
Data de Resolução (Filha)	
Qt Pontos Função de DMS ou DNS Implantadas

**Comment by alvarobasto** [comment]
Ao clicar no nome da unidade, uma nova aba é aberta com uma visão do Analyzer.
