### ISSUE TITLE
Incluir linha com Médias por GEA/CEDES nas tabelas

### ISSUE THREAD

**Issue by alex-sousa** [llms/sialg#20]
- Na Tabela GEA, os registros GEABR10, GEARJ10 e GEASP10 na tabela deverão apresentar média da nota final das demais GEA agrupadas por UF (BR, RJ, SP), participando do ranking e contendo medalhas, junto às demais.

- Na Tabela CEDES, a CEDESBR, CEDESRJ e CEDESSP devem aparecer nas primeiras linhas da tabela, sem nota final, sem medalha e sem ranking.

**Comment by JulianaCarvalho** [comment]
Alex boa tarde, tudo bem?
Na tabela GEA você poderia explicar mais detalhadamente como seria essa organização? Porque os registros GEABR10, GEARJ10 e GEASP10 estão na tabela com um resultado. Você quer mudar o valor deles para que seja uma média geral das unidades GEABR, GEARJ e GEASP? Esses registros vão ficar ordenados de acordo com o ranking ou nas primeiras linhas como ocorre no CEDES? 
![gea](https://cloud.githubusercontent.com/assets/11621011/22559712/c3f4f25a-e950-11e6-8f7b-162cd7db60a7.PNG)

**Comment by alex-sousa** [comment]
Oi Juliana! Boa tarde!
No caso a GEA 10 seria o totalizador da GEASP, GEARJ e GEABR e substituiria o valor que tem lá. É como se você excluisse as que constam lá e fizesse um union com as médias. No caso essas "unidades" também fariam parte do ranking e seriam ordenadas como uma das unidades. 

Esse acompanhamento é diferente das CEDES, que tem esse totalizador nas primeiras linhas.

**Comment by alex-sousa** [comment]
No caso a GEA10 seria a média de todas as unidades daquela UF, mas excluindo os valores reais das GEA10 que tem lá. Ficou claro? Hahah
O acompanhamento deles já usa esse conceito, ao invés de só GEASP ou GEARJ e eles querem manter dessa forma.

**Comment by JulianaCarvalho** [comment]
Entendi! :)

**Comment by JulianaCarvalho** [comment]
closes #20
