### ISSUE TITLE
Ajustar a função clique das tabelas de CEDES e GEA.

### ISSUE THREAD

**Issue by alvarobasto** [llms/sialg#23]
Temos que habilitar o clique nos valores das tabelas. Passando a sua respectiva unidade + a posição da coluna.
![captura de tela 2017-02-15 as 10 30 14](https://cloud.githubusercontent.com/assets/14278123/22976577/1f30fbbe-f36a-11e6-93db-33e2f3cf2421.png)

**Comment by JulianaCarvalho** [comment]
closes #23
