### ISSUE TITLE
Verificar a cor de fundo das células da coluna Nota Final 

### ISSUE THREAD

**Issue by alex-sousa** [llms/sialg#26]
Verificar a cor de fundo das células da coluna Nota Final nas tabelas GEA e CEDES para seguir os mesmos ranges e cores das demais colunas. 

Os percentuais abaixo são com relação ao valor do parâmetro Metas da Nota Final

% Resultado >= 120%	COR AZUL	MUITO SATISFATÓRIO
% Resultado >= 100% e < 120% COR VERDE	SATISFATÓRIO
% Resultado >= 70% e < 100% COR AMARELA	NECESSITA DE MELHORIAS
% Resultado < 70%	COR VERMELHA	NECESSITA DE MELHORIAS IMPORTANTES

**Comment by JulianaCarvalho** [comment]
closes #26
