### ISSUE TITLE
Verificar Valores das GEA10e SUCTI na tabela

### ISSUE THREAD

**Issue by alex-sousa** [llms/sialg#27]
Nos dois casos o valor apresentado são o da Nota Final, mas valores não batem com os dos dials da aba Geral.
GEABR = GEABR10
GEASP = GEASP10
GEARJ = GEARJ10

![image](https://cloud.githubusercontent.com/assets/22936150/23210212/5940fe82-f8db-11e6-943f-752031d200a0.png)

![image](https://cloud.githubusercontent.com/assets/22936150/23210201/476762b4-f8db-11e6-88e0-8bff2ac70eb9.png)

**Comment by JulianaCarvalho** [comment]
closed #27
