### ISSUE TITLE
Inserir Card e Gráfico de Atendimento na Aba Geral

### ISSUE THREAD

**Issue by alex-sousa** [llms/sialg#28]
As definições do gráfico de tendência foram alteradas, vamos trabalhar com a nota final, assim englobamos todos os indicadores. E depois evoluímos outras visões.

	Tipo de gráfico: Linha
	Dados apresentados: Meta fixada, Nota atingida e tendência.
	Período: mensal com a marca do trimestre
	Exibição de hint com os valores 
	Apresentação default de quatro gráficos: GEABR, GEARJ, GEASP e SUCTI
o	a cada 10 segundos um gráfico é apresentado 
o	permitir os comandos de voltar, pausar e avançar
	Permitir apresentação do gráfico para a GEA selecionada na combo
	Por agora se tratar de Nota final, a meta fixada é 10. Inserir parâmetro ao lado da Combo que permita alterar a Meta

Para facilitar o entendimento, desenhei o seguinte protótipo:
![grafico atendimento](https://cloud.githubusercontent.com/assets/22936150/23257576/3dd84380-f9a3-11e6-9424-36156871d916.jpg)

**Comment by JulianaCarvalho** [comment]
Closed #28
