### ISSUE TITLE
Alterar Fórmula do Indicador Agilidade - Efetividade

### ISSUE THREAD

**Issue by alex-sousa** [llms/sialg#29]
No indicador Agilidade - Efetividade no Planejamento aplicar 1- no início da fórmula (exemplo: 1-( Qt DN Replanejadas implantadas no período  / Qt DN Implantadas no Período))
O indicador na verdade será representado por 100%- o % calculado

A fórmula deve ser alterada nos gráficos e tabelas que apresentam o índice.

**Comment by JulianaCarvalho** [comment]
Alex, por favor, depois me avisa se está correto para que eu possa fechar a issue.

**Comment by alex-sousa** [comment]
É isso mesmo, Juliana!

**Comment by alex-sousa** [comment]
obrigado!
